services:
    xdmod:
        image: tools-ext-01.ccr.xdmod.org/xdmod:x86_64-rockylinux8.10.20240528-v11.0.2-3-01
        hostname: xdmod
        container_name: xdmod
        networks:
            - jupyter-net
        shm_size: 2g
        stdin_open: true
        tty: true
        command: sleep infinity
        expose:
            - 443
        volumes:
            - ./web-setup/xdmod.crt:/etc/pki/tls/certs/xdmod.crt
            - ./web-setup/xdmod.key:/etc/pki/tls/private/xdmod.key
        secrets:
            - xdmod-private.pem
    jupyterhub:
        build: 
            context: .
            dockerfile: jupyterhub/Dockerfile
        hostname: jupyterhub
        container_name: jupyterhub
        networks:
            - jupyter-net
        volumes:
            - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
            - "/var/run/docker.sock:/var/run/docker.sock"
        expose:
            - 8001
        secrets:
            - jwt-private-key
            - xdmod-public
    chart-service:
       build: ./chart-service
       hostname: chart-service
       container_name: chart-service
       networks:
            - jupyter-net
       expose:
            - 2323
       environment:
            JUPYTERHUB_API_TOKEN: 'c780c3d34d334706b9988b5f5211d49d'
    web-server:
       image: nginx:1.14.1
       hostname: web-server
       container_name: web-server
       networks:
            - jupyter-net
       ports:
            - "8443:443"
       volumes:
            - ./web-setup/dhparams.pem:/etc/xdmod/dhparams.pem
            - ./web-setup/xdmod.crt:/etc/xdmod/xdmod.crt
            - ./web-setup/xdmod.key:/etc/xdmod/xdmod.key
            - ./web-setup/nginx.conf:/etc/nginx/nginx.conf
networks:
    jupyter-net:
        name: jupyter-net
secrets:
    jwt-public-key:
        file: ./jwt-service/jwt-key.pub
    jwt-private-key:
        file: ./jwt-service/jwt-key
    xdmod-private.pem:
        file: ./web-setup/xdmod-private.pem
    xdmod-public:
        file: ./web-setup/xdmod-public.pem
