events{
	worker_connections 1024;
}
http{
    map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
    }
    server {
        listen *:80;
        server_name access-dev-proxy.ccr.xdmod.org;
        add_header "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload";
        add_header "X-Content-Type-Options" "nosniff";
        access_log /var/log/nginx/testserver.log;
        error_log /var/log/nginx/testserver-error.log;
        location / {
            return 301 https://hostrequest_uri;
            }
    }
    server {
        listen *:443 ssl http2;
        server_name server;
        ssl on;
        ssl_certificate /etc/xdmod/xdmod.crt;
        ssl_certificate_key /etc/xdmod/xdmod.key;
        ssl_dhparam /etc/xdmod/dhparams.pem;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        index index.html index.htm index.php;
        access_log /var/log/nginx/testserver.log;
        error_log /var/log/nginx/testserver.log;
        add_header "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload";
        add_header "X-Content-Type-Options" "nosniff";
        location /jupyter/ {
            proxy_pass http://jupyterhub:8000;
            proxy_read_timeout 90s;
            proxy_connect_timeout 90s;
            proxy_send_timeout 90s;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /jupyter/user/ {
            proxy_pass http://jupyterhub:8000;
            proxy_read_timeout 90s;
            proxy_connect_timeout 90s;
            proxy_send_timeout 90s;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        location / {
            proxy_pass https://xdmod:443;
            proxy_ssl_server_name on;
            proxy_ssl_name $host;
            proxy_ssl_session_reuse off;
            proxy_read_timeout 300s;
            proxy_connect_timeout 90s;
            proxy_send_timeout 90s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Proxy "";
        }
	location /jupyter/hub/{
	    proxy_pass http://jupyterhub:8000;
            proxy_read_timeout 90s;
            proxy_connect_timeout 90s;
            proxy_send_timeout 90s;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
    }

}


